### PR TITLE
Add redirect for book of Mozilla; just for lulz

### PR DESCRIPTION
**Pull request by tofumatt**

### CODE REVIEW

**Review by mykmelez — APPROVED** [review]

**Comment by mykmelez** [comment]
Merged! However, I suspect that this won't work, because the extension redirects moz: requests to GitHub Pages, which then redirects them to the URL specified by the hash in index.html, and I don't think web content can direct a user to an about: URL.

Anyway, we can test it shortly, once GitHub Pages gets updated.

**Comment by tofumatt** [comment]
Yeah I was curious about that. Testing in production ftw! 😉

**Comment by mykmelez** [comment]
It's updated now, and I just tested it: it works! Perhaps web content redirects to about: links are only restricted if the about: page is privileged? In any case, it's working fine, so woot!

**Comment by mykmelez** [comment]
Note for my future reference: when I merged this, GitHub emailed me to report a "Page build failure" with the error message "Page build failed."

According to https://help.github.com/articles/troubleshooting-github-pages-builds/, "If your GitHub Pages site fails to build on our servers or encounters other errors, you can troubleshoot your build error by reviewing common problems or specific error messages. You can also view Jekyll build error messages by email, in your repository, on the command line, or using a third party service."

None of those seemed to be a problem, so I pushed a trivial whitespace change, and that build succeeded. I suspect this was an unrelated failure on GitHub's part, perhaps due to an infrastructure issue, especially since https://status.github.com/https://status.github.com/ reports that Pages build failures spiked last night and are increasing this morning:

screen shot 2017-01-27 at 09 32 50

**Pull request merged**
