### PR TITLE
Adding bugzilla quicksearch

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
I don't know if we can handle the search parameter with something like: `moz://bugzilla/1332182`

**Comment by mykmelez** [comment]
> I don't know if we can handle the search parameter with something like: moz://bugzilla/1332182

We could, but it'd take some extra logic in index.html's redirection code, which currently just loads the URL corresponding to the "key" after the leading `moz:lla/` in the value of the *u* parameter.

So `moz://a/something` redirects to `https://mozilla.github.io/moz-handler/?u=moz%3A%2F%2Fa%2Fsomething`, and index.html then extracts the string `something` from that and looks it up in the hash of URLs to determine which URL to load.

If you wanted to enable loading a particular bug by number and/or searching for bugs by search terms, then you'd need to add logic that looks for a URL of the form `moz://a/bug/SOMETHING` and then either loads the bug with the number SOMETHING (if SOMETHING is a number) or search for the terms (if SOMETHING is a sequence of search terms).

**Comment by Natim** [comment]
> So moz://a/something redirects to https://mozilla.github.io/moz-handler/?u=moz%3A%2F%2Fa%2Fsomething, and index.html then extracts the string something from that and looks it up in the hash of URLs to determine which URL to load.

👍

**Comment by Natim** [comment]
> If you wanted to enable loading a particular bug by number and/or searching for bugs

It is automatic if you use quicksearch

**Comment by Natim** [comment]
Do you want me to add this logic or do you think it is irrelevant for this extension?

**Comment by mykmelez** [comment]
> Do you want me to add this logic or do you think it is irrelevant for this extension?

I'd be happy for you to add this logic!

**Pull request closed without merging**
